### 게임 아이디로 선수 불러오기

localhost:8585/api/v1/players/1/pageNo/1/amount/9
Accept: application/json

### 선수 등록

POST localhost:8585/api/v1/players
Content-Type: application/json

{
  "gameId": 7,
  "playerImgPath": "a",
  "playerName": "데자와"
}

### 선수 등록

POST localhost:8585/api/v1/players
Content-Type: application/json

{
  "gameId": 1,
  "playerImgPath": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWmr4ikE7hzXQvgC0lbeJXhCErF5V0bH_87Vh-0Mf6mQ&s",
  "playerName": "솔의눈"
}
